import * as mongoose from 'mongoose';
import {
	Equals,
	IsArray,
	IsEmpty, IsEnum,
	IsNotEmpty,
	IsNumber,
	IsOptional,
	IsString,
	Matches,
	ValidateNested,
	Length,
	IsBoolean
} from 'class-validator';
import { ApiModelProperty, ApiModelPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

export interface CommonResponseModel {
	response_code: number;
	response_data: any;
	extra?: string;
}

export enum AdminSettings {
	DEFAULT_PAGE_NUMBER = 1,
	DEFAULT_PAGE_LIMIT = 10,
}

export enum UserSettings {
	DEFAULT_PAGE_NUMBER = 0,
	DEFAULT_PAGE_LIMIT = 10,
}

export class AdminQuery {
	page?: number;
	limit?: number;
	q?: string;
}

export class UserQuery {
	page?: number;
	limit?: number;
}
export class ResponseSuccessMessage {
	@IsString()
	@ApiModelProperty()
	response_code: string;

	@IsString()
	@ApiModelProperty()
	response_data: string;
}

export class ResponseBadRequestMessage {
	@IsNumber()
	@ApiModelProperty()
	status: number;

	@ApiModelProperty()
	errors: Array<string>;

}
export class ResponseErrorMessage {
	@IsNumber()
	@ApiModelProperty()
	status: number;

	@IsString()
	@ApiModelProperty()
	message: string;
}

export class UploadImageDTO {
	@ApiModelPropertyOptional()
	type: string;
}

export class UploadImageResponseDTO {
	@IsString()
	@ApiModelProperty()
	url: string;

	@IsString()
	@ApiModelProperty()
	key: string;

	@IsString()
	@ApiModelProperty()
	filePath: string;
}
export class UploadImagesResponseDTO {
	@IsArray()
	@ApiModelProperty({ type: [UploadImageResponseDTO] })
	productImages: Array<UploadImageResponseDTO>
}
export class TwilioResponseDTO {
	@IsBoolean()
	@ApiModelProperty()
	isError: boolean

	@IsString()
	@ApiModelProperty()
	data: string
}

export class UpdateOneManyDTO {
	n: number;
	nModified: number;
	opTime: object;
	electionId: string;
	ok: number;
	operationTime: string;
	$clusterTime: object
}

export enum LanguageJsonType {
	BACKEND = 'backendJson',
	CMS = 'cmsJson',
	WEB = 'webJson',
	USER = 'mobAppJson',
	DELIVERY = 'deliveyAppJson'
}

export enum UserRoles {
	ADMIN = 'ADMIN',
	USER = 'USER',
	DELIVERY_BOY = 'DELIVERY_BOY'
}

export enum FileDownloadStatus {
	Processing = "Processing",
	Completed = "Completed",
	Pending = "Pending"
}

export enum CouponType {
	PERCENTAGE = 'PERCENTAGE'
}

export enum TaxName {
	GST = 'GST'
}


export enum ResponseMessage {
	ADDRESS_SAVED = 'ADDRESS_SAVED',
	ADDRESS_UPDATED = 'ADDRESS_UPDATED',
	ADDRESS_DELETED = 'ADDRESS_DELETED',
	ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
	ADDDRESS_DELIVERY_LOCATION_NOT_AVAILABLE = 'ADDDRESS_DELIVERY_LOCATION_NOT_AVAILABLE',
	BANNER_SAVED = 'BANNER_SAVED',
	BANNER_UPDATED = 'BANNER_UPDATED',
	BANNER_DELETED = 'BANNER_DELETED',
	BANNER_NOT_FOUND = 'BANNER_NOT_FOUND',
	BANNER_CATEGORY_ID_MISSING = 'BANNER_CATEGORY_ID_MISSING',
	BANNER_PRODUCT_ID_MISSING = 'BANNER_PRODUCT_ID_MISSING',
	BUSINESS_UPDATED = 'BUSINESS_UPDATED',
	CATEGORY_SAVED = 'CATEGORY_SAVED',
	CATEGORY_UPDATED = 'CATEGORY_UPDATED',
	CATEGORY_DELETED = 'CATEGORY_DELETED',
	CATEGORY_STATUS_UPDATED = 'CATEGORY_STATUS_UPDATED',
	CATEGORY_ALREADY_EXIST = 'CATEGORY_ALREADY_EXIST',
	CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
	CATEGORY_NOT_DELETED_HAVE_SUBCATEGORY = 'CATEGORY_NOT_DELETED_HAVE_SUBCATEGORY',
	CATEGORY_NOT_DELETED_HAVE_PRODUCT = 'CATEGORY_NOT_DELETED_HAVE_PRODUCT',
	CATEGORY_NOT_DELETED_HAVE_BANNER = 'CATEGORY_NOT_DELETED_HAVE_BANNER',
	CATEGORY_NOT_DELETED_HAVE_DEAL = 'CATEGORY_NOT_DELETED_HAVE_DEAL',
	CART_ADDED_PRODUCT = 'CART_ADDED_PRODUCT',
	CART_UPDATED_PRODUCT = 'CART_UPDATED_PRODUCT',
	CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
	CART_DELETED = 'CART_DELETED',
	CART_VERIFIED = 'CART_VERIFIED',
	CART_NOT_FOUND = 'CART_NOT_FOUND',
	CART_ITEM_OUT_OF_STOCK = 'CART_ITEM_OUT_OF_STOCK',
	CART_ITEM_LEFT = 'CART_ITEM_LEFT',
	COUPON_SAVED = 'COUPON_SAVED',
	COUPON_UPDATED = 'COUPON_UPDATED',
	COUPON_DELETED = 'COUPON_DELETED',
	COUPON_STATUS_UPDATED = 'COUPON_STATUS_UPDATED',
	COUPON_ALREADY_EXIST = 'COUPON_ALREADY_EXIST',
	COUPON_EXPIRED = 'COUPON_EXPIRED',
	COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
	CURRENCY_INVALID = "CURRENCY_INVALID",
	DAYS_SUNDAY = 'DAYS_SUNDAY',
	DAYS_MONDAY = 'DAYS_MONDAY',
	DAYS_TUESDAY = 'DAYS_TUESDAY',
	DAYS_WEDNESDAY = 'DAYS_WEDNESDAY',
	DAYS_THURSDAY = 'DAYS_THURSDAY',
	DAYS_FRIDAY = 'DAYS_FRIDAY',
	DAYS_SATURDAY = 'DAYS_SATURDAY',
	DEAL_SAVED = 'DEAL_SAVED',
	DEAL_UPDATED = 'DEAL_UPDATED',
	DEAL_STATUS_UPDATED = 'DEAL_STATUS_UPDATED',
	DEAL_DELETED = 'DEAL_DELETED',
	DEAL_ALREADY_EXIST = 'DEAL_ALREADY_EXIST',
	DEAL_NOT_FOUND = 'DEAL_NOT_FOUND',
	DEAL_CATEGORY_ID_MISSING = 'DEAL_CATEGORY_ID_MISSING',
	DEAL_PRODUCT_ID_MISSING = 'DEAL_CATEGORY_ID_MISSING',
	DELIVERY_BOY_NOT_FOUND = 'DELIVERY_BOY_NOT_FOUND',
	DELIVERY_BOY_ALREADY_ACCEPTED_ORDER = 'DELIVERY_BOY_ALREADY_ACCEPTED_ORDER',
	DELIVERY_BOY_ALREADY_RATED_BY_USER = 'DELIVERY_BOY_ALREADY_RATED_BY_USER',
	DELIVERY_BOY_NOTIFY_ORDER_ASSIGNED_TITLE = 'DELIVERY_BOY_NOTIFY_ORDER_ASSIGNED_TITLE',
	DELIVERY_BOY_NOTIFY_ORDER_ASSIGNED_DESC = 'DELIVERY_BOY_NOTIFY_ORDER_ASSIGNED_DESC',
	DELIVERY_BOY_STATUS_UPDATED = 'DELIVERY_BOY_STATUS_UPDATED',
	DELIEVRY_SLOT_NOT_SELECTED = 'DELIEVRY_SLOT_NOT_SELECTED',
	DELIEVRY_SLOT_NOT_AVAILABLE = 'DELIEVRY_SLOT_NOT_AVAILABLE',
	FAVOURITE_SAVED = 'FAVOURITE_SAVED',
	FAVOURITE_DELETED = 'FAVOURITE_DELETED',
	FAVOURITE_ALREADY_ADDED_PRODUCT = 'FAVOURITE_ALREADY_ADDED_PRODUCT',
	FILE_IMPORT_START = "FILE_IMPORT_START",
	FILE_TYPE_ERROR = "FILE_TYPE_ERROR",
	IMAGE_URL_MUST = "IMAGE_URL_MUST",
	LANGUAGE_ALREADY_EXIST = 'LANGUAGE_ALREADY_EXIST',
	LANGUAGE_VALIDATED = 'LANGUAGE_VALIDATED',
	LANGUAGE_SAVED = 'LANGUAGE_SAVED',
	LANGUAGE_UPDATED = 'LANGUAGE_UPDATED',
	LANGUAGE_DELETED = 'LANGUAGE_DELETED',
	LANGUAGE_NOT_FOUND = 'LANGUAGE_NOT_FOUND',
	LANGUAGE_DEFAULT_UPDATED = 'LANGUAGE_DEFAULT_UPDATED',
	LANGUAGE_STATUS_UPDATED = 'LANGUAGE_STATUS_UPDATED',
	MOBILE_NUMBER_UPDATED_SUCCESSFULLY = 'MOBILE_NUMBER_UPDATED_SUCCESSFULLY',
	MOBILE_NUMBER_SUCCESSFULLY_VERIFIED = 'MOBILE_NUMBER_SUCCESSFULLY_VERIFIED',
	MOBILE_NUMBER_NOT_VERIFIED = 'MOBILE_NUMBER_NOT_VERIFIED',
	ORDER_PLACED = 'ORDER_PLACED',
	ORDER_MINIMUM_AMOUNT_PLACE_ORDER = 'ORDER_MINIMUM_AMOUNT_PLACE_ORDER',
	ORDER_PAYMENT_ERROR = 'ORDER_PAYMENT_ERROR',
	ORDER_NOT_DELIVERED = 'ORDER_NOT_DELIVERED',
	ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
	ORDER_STATUS_INVALID = 'ORDER_STATUS_INVALID',
	ORDER_ALREADY_DELIVERED = 'ORDER_ALREADY_DELIVERED',
	ORDER_CANCELLED = 'ORDER_CANCELLED',
	ORDER_UPDATED = 'ORDER_UPDATED',
	ORDER_ALREADY_ASSIGNED = 'ORDER_ALREADY_ASSIGNED',
	ORDER_ASSIGNED_TO_DELIVERY_BOY = 'ORDER_ASSIGNED_TO_DELIVERY_BOY',
	ORDER_ACCEPTED_BY_DELIVERY_BOY = 'ORDER_ACCEPTED_BY_DELIVERY_BOY',
	ORDER_REJECTED_BY_DELIVERY_BOY = 'ORDER_REJECTED_BY_DELIVERY_BOY',
	OTP_SENT_TO_NEW_MOBILE_NUMBER = "OTP_SENT_TO_NEW_MOBILE_NUMBER",
	OTP_SENT_TO_REGISTERED_MOBILE_NUMBER = 'OTP_SENT_TO_REGISTERED_MOBILE_NUMBER',
	ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
	PAGE_UPADTED = 'PAGE_UPADTED',
	PAYMENT_ID_NOT_FOUND = 'PAYMENT_ID_NOT_FOUND',
	PRODUCT_DISABLED_NOT_AVAILABLE_FOR_DELIVERY = 'PRODUCT_DISABLED_NOT_AVAILABLE_FOR_DELIVERY',
	PRODUCT_ALREADY_EXIST = 'PRODUCT_ALREADY_EXIST',
	PRODUCT_SAVED = 'PRODUCT_SAVED',
	PRODUCT_UPDATED = 'PRODUCT_UPDATED',
	PRODUCT_STATUS_UPDATED = 'PRODUCT_STATUS_UPDATED',
	PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
	PRODUCT_NOT_DELETED_HAVE_BANNER = 'PRODUCT_NOT_DELETED_HAVE_BANNER',
	PRODUCT_NOT_DELETED_HAVE_DEAL = 'PRODUCT_NOT_DELETED_HAVE_DEAL',
	PRODUCT_DELETED = 'PRODUCT_DELETED',
	PRODUCT_IMPORTED_SUCCESSFULLY = 'PRODUCT_IMPORTED_SUCCESSFULLY',
	PRODUCT_NOT_BOUGHT = 'PRODUCT_NOT_BOUGHT',
	PUSH_NOTIFICATION_SENT = 'PUSH_NOTIFICATION_SENT',
	PUSH_NOTIFICATION_NOT_SENT = 'PUSH_NOTIFICATION_NOT_SENT',
	RATING_SAVED = 'RATING_SAVED',
	RATING_ALREADY_GIVEN = 'RATING_ALREADY_GIVEN',
	REQUIRED_VALID_MOBILE_NUMBER = 'REQUIRED_VALID_MOBILE_NUMBER',
	SETTING_CURRENCY_UPDATED = 'SETTING_CURRENCY_UPDATED',
	SETTING_DELIVERY_TAX_UPDATED = 'SETTING_DELIVERY_TAX_UPDATED',
	SETTING_DELIVERY_TIME_SLOTS_UPDATED = 'SETTING_DELIVERY_TIME_SLOTS_UPDATED',
	SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
	SUB_CATEGORY_SAVED = 'SUB_CATEGORY_SAVED',
	SUB_CATEGORY_UPDATED = 'SUB_CATEGORY_UPDATED',
	SUB_CATEGORY_STATUS_UPDATED = 'SUB_CATEGORY_STATUS_UPDATED',
	SUB_CATEGORY_NOT_FOUND = 'SUB_CATEGORY_NOT_FOUND',
	SUB_CATEGORY_DELETED = 'SUB_CATEGORY_DELETED',
	SUB_CATEGORY_ALREADY_EXIST = 'SUB_CATEGORY_ALREADY_EXIST',
	SUB_CATEGORY_NOT_DELETED_HAVE_PRODUCT = 'SUB_CATEGORY_NOT_DELETED_HAVE_PRODUCT',
	UNABLE_TO_SEND_OTP = 'UNABLE_TO_SEND_OTP',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_NOTIFY_ORDER_PLACED_TITLE = 'USER_NOTIFY_ORDER_PLACED_TITLE',
	USER_NOTIFY_ORDER_PLACED_DESC = 'USER_NOTIFY_ORDER_PLACED_DESC',
	USER_NOTIFY_ORDER_CONFIRMED_TITLE = 'USER_NOTIFY_ORDER_CONFIRMED_TITLE',
	USER_NOTIFY_ORDER_CONFIRMED_DESC = 'USER_NOTIFY_ORDER_CONFIRMED_DESC',
	USER_NOTIFY_ORDER_OUT_OF_DELIVERY_TITLE = 'USER_NOTIFY_ORDER_OUT_OF_DELIVERY_TITLE',
	USER_NOTIFY_ORDER_OUT_OF_DELIVERY_DESC = 'USER_NOTIFY_ORDER_OUT_OF_DELIVERY_DESC',
	USER_NOTIFY_ORDER_DELIVERED_TITLE = 'USER_NOTIFY_ORDER_DELIVERED_TITLE',
	USER_NOTIFY_ORDER_DELIVERED_DESC = 'USER_NOTIFY_ORDER_DELIVERED_DESC',
	USER_NOTIFY_ORDER_CANCELLED_TITLE = 'USER_NOTIFY_ORDER_CANCELLED_TITLE',
	USER_NOTIFY_ORDER_CANCELLED_DESC = 'USER_NOTIFY_ORDER_CANCELLED_DESC',
	USER_EMAIL_VERIFY_SENT = 'USER_EMAIL_VERIFY_SENT',
	USER_EMAIL_VERIFY_NOT_SENT = 'USER_EMAIL_VERIFY_NOT_SENT',
	USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
	USER_ACCOUNT_BLOCKED = 'USER_ACCOUNT_BLOCKED',
	USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',
	USER_EMAIL_OR_PASSWORD_INVALID = 'USER_EMAIL_OR_PASSWORD_INVALID',
	USER_EMAIL_INVALID = 'USER_EMAIL_INVALID',
	USER_EMAIL_VERIFY_SUBJECT = 'USER_EMAIL_VERIFY_SUBJECT',
	USER_EMAIL_VERIFY_BODY = 'USER_EMAIL_VERIFY_BODY',
	USER_EMAIL_VERIFY_BUTTON = 'USER_EMAIL_VERIFY_BUTTON',
	USER_FORGOT_PASSWORD_OTP_SENT_EMAIL = 'USER_FORGOT_PASSWORD_OTP_SENT_EMAIL',
	USER_FORGOT_PASSWORD_OTP_NOT_SENT_EMAIL = 'USER_FORGOT_PASSWORD_OTP_NOT_SENT_EMAIL',
	USER_FORGOT_PASSWORD_OTP_INVALID = 'USER_FORGOT_PASSWORD_OTP_INVALID',
	USER_FORGOT_PASSWORD_OTP_EXPIRED = 'USER_FORGOT_PASSWORD_OTP_EXPIRED',
	USER_FORGOT_PASSWORD_OTP_VERIFIED = 'USER_FORGOT_PASSWORD_OTP_VERIFIED',
	USER_FORGOT_PASSWORD_EMAIL_SUBJECT = 'USER_FORGOT_PASSWORD_EMAIL_SUBJECT',
	USER_FORGOT_PASSWORD_EMAIL_BODY = 'USER_FORGOT_PASSWORD_EMAIL_BODY',
	USER_EMAIL_VERIFIED_ALREADY = 'USER_EMAIL_VERIFIED_ALREADY',
	USER_EMAIL_VERIFIED_SUCCESSFULLY = 'USER_EMAIL_VERIFIED_SUCCESSFULLY',
	USER_EMAIL_VERIFY_EXPIRED = 'USER_EMAIL_VERIFY_EXPIRED',
	USER_EMAIL_VERIFICATION_CODE_INVALID = 'USER_EMAIL_VERIFICATION_CODE_INVALID',
	USER_RESET_PASSWORD_INVALID_TOKEN = 'USER_RESET_PASSWORD_INVALID_TOKEN',
	USER_CURRENT_PASSWORD_INCORRECT = 'USER_CURRENT_PASSWORD_INCORRECT',
	USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
	USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
	USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
	USER_STATUS_UPDATED = 'USER_STATUS_UPDATED',
	USER_LOGOUT = 'USER_LOGOUT',
	USER_EMAIL_ALREADY_EXIST = 'USER_EMAIL_ALREADY_EXIST',
	USER_MOBILE_ALREADY_EXIST = 'USER_MOBILE_ALREADY_EXIST',
	USER_MOBILE_SAME = 'USER_MOBILE_SAME',
	USER_MOBILE_NOT_REGISTERED = 'USER_MOBILE_NOT_REGISTERED',
	USER_PASSWORD_INVALID = 'USER_PASSWORD_INVALID',
	USER_LANGUAGE_UPDATED = 'USER_LANGUAGE_UPDATED',
	USER_PROFILE_IMAGE_DELETED = 'USER_PROFILE_IMAGE_DELETED',
	VERIFICATION_SENT_TO_MOBILE_NUMBER = 'VERIFICATION_SENT_TO_MOBILE_NUMBER',
	WALLET_INSUFFICENT_AMOUNT = 'WALLET_INSUFFICENT_AMOUNT',
	WRONG_OTP = 'WRONG_OTP',
	DEFAULT_LANGUAGE_NOT_DELETED = 'DEFAULT_LANGUAGE_NOT_DELETED',
	ENTER_REGISTER_MOBILE_NUMBER = "ENTER_REGISTER_MOBILE_NUMBER",
	DELIVERY_BOY_CREATED_SUCCESSFULLY = "DELIVERY_BOY_CREATED_SUCCESSFULLY",
	POS_MISSING_QUERY_PARAMETER = 'MISSING QUERY PARAMETER',
	POS_SALE_CREATED = 'POINT OF SALE CREATED',

}